-- Seed jobs data based on user request
-- Inserts 14 IT-related job postings

INSERT INTO public.jobs (
    title,
    company,
    location,
    type,
    work_type,
    category,
    salary_range,
    description,
    target_courses,
    status,
    posted_by
) VALUES
(
    'IT Technician',
    'TechSupport Solutions',
    'Quezon City, Philippines',
    'Full-time',
    'On-site',
    'Information Technology',
    '$52,455 per year',
    '**Primary duties:** An IT technician collaborates with support specialists to analyze and diagnose computer issues. They also monitor processing functions, install relevant software and perform tests on computer equipment and applications when necessary. They may also train a company''s employees, clients and other users on a new program or function as well.\n\n**Requirements:** IT technicians must earn an associate degree in IT or a bachelor''s degree in computer science or networking. Technicians render services for IT companies depending on the industry they choose to work in and may need to learn more about database programming to give themselves an advantage in an entry-level role.',
    ARRAY['BSIT', 'BSCS', 'BSCrim'], -- Added randomly to distribute visibility
    'active',
    (SELECT id FROM auth.users LIMIT 1) -- Assign to first user found just to have a posted_by, or NULL if acceptable
),
(
    'Support Specialist',
    'Global Connect',
    'Makati City, Philippines',
    'Full-time',
    'Remote',
    'Customer Support',
    '$47,368 per year',
    '**Primary duties:** Support specialists are responsible for reviewing and solving computer network and hardware problems for a business. They can work in a variety of industries to provide general support to a company''s employees or at a technology or software-as-a-service (SaaS) company to provide technical support on user experience issues that require technical assistance.\n\n**Requirements:** Support specialists typically obtain a bachelor''s degree in IT or computer science. Having a certificate or an associate degree paired with relevant professional experience may also be acceptable.',
    ARRAY['BSIT', 'BSBA'],
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Quality Assurance Tester',
    'GameDev Studio',
    'BGC, Taguig',
    'Contract',
    'On-site',
    'Quality Assurance',
    '$70,299 per year',
    '**Primary duties:** Quality assurance testers are technicians or engineers who check software products to see if they''re up to industry standards and free of any issues. This role is common for gaming systems, mobile applications and other technology that needs further testing and maintenance when recommended.\n\n**Requirements:** Many quality assurance testers have a bachelor''s degree in software design, engineering or computer science. Testers can work on different software for IT companies, which may influence what degree or specialization they pursue. These professionals should also have excellent time management and communication skills to help document test cases.',
    ARRAY['BSCS', 'BSIT'],
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Web Developer',
    'Creative Web Co.',
    'Remote',
    'Full-time',
    'Remote',
    'Web Development',
    '$77,791 per year',
    '**Primary duties:** Web developers design the appearance, navigation and content organization of a website. They use coding languages such as HTML, CSS and JavaScript to manage graphics, applications and content that address a client''s needs.\n\n**Requirements:** Many web developers earn an associate degree in web development or another relevant IT field. Some may pursue a bachelor''s degree in IT or another business field. Others may develop their web design skills through certificate programs or self-paced learning. To secure employment, previous experience and a portfolio of work are often required.',
    ARRAY['BSIT', 'BSCS'],
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'IT Security Specialist',
    'CyberSecure Inc.',
    'Pasig City',
    'Full-time',
    'Hybrid',
    'Cybersecurity',
    '$82,514 per year',
    '**Primary duties:** IT security specialists work in various industries to build and maintain digital protective measures on intellectual property and data that belong to an organization. They help companies create contingency plans in case information gets hacked from their networks and servers. These professionals also create strategies to troubleshoot problems as they arise.\n\n**Requirements:** A bachelor''s degree or professional certification is often required. Courses may involve math, programming and operating systems and certifications offered by the Information Systems Security Certification Consortium (ISC2).',
    ARRAY['BSIT', 'BSCS', 'BSCrim'],
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Computer Programmer',
    'CodeCrafters',
    'BGC, Taguig',
    'Full-time',
    'On-site',
    'Software Development',
    '$68,620 per year',
    '**Primary duties:** A computer programmer is someone who writes new computer software using coding languages like HTML, JavaScript and CSS. Video game software can be updated to improve online gameplay, which is an opportunity for programmers to troubleshoot problems experienced by gamers after the game is released to the general public.\n\n**Requirements:** A programmer typically completes a bachelor''s degree in computer science and an internship to build their skills. Certifications are also strongly encouraged, and there are many coding academies to choose from.',
    ARRAY['BSCS', 'BSIT'],
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Systems Analyst',
    'FinTech Solutions',
    'Makati City',
    'Full-time',
    'Hybrid',
    'Analysis',
    '$79,891 per year',
    '**Primary duties:** A systems analyst reviews design components and uses their knowledge of information technology to solve business problems. They identify ways that infrastructure needs to change to streamline business and IT operations. They can also assist technicians in training staff to implement the changes they propose.\n\n**Requirements:** A bachelor''s degree in computer science or a related IT field is often required. Coursework in business administration, management and finance may help these professionals better apply their IT knowledge to improving business practices.',
    ARRAY['BSCS', 'BSIT', 'BSBA'],
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Network Engineer',
    'NetWorks Asia',
    'Pasay City',
    'Full-time',
    'On-site',
    'Infrastructure',
    '$95,178 per year',
    '**Primary duties:** Network engineers work on the day-to-day maintenance and development of a company''s computer network, utilizing their skills to make the network available and efficient for all employees within an organization.\n\n**Requirements:** These professionals typically need a bachelor''s degree in computer science or information systems to understand the functions of a network and become familiar with potential solutions needed to maintain one. Some employers may also require a Master of Business Administration (MBA) degree for those who work with other internal stakeholders of the organization to determine the best technology practices.',
    ARRAY['BSIT', 'BSCS'],
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Software Engineer',
    'Innovate Tech',
    'Remote',
    'Full-time',
    'Remote',
    'Software Development',
    '$108,896 per year',
    '**Primary duties:** Software engineers apply their knowledge of mathematics and computer science to create and improve new software. They may work on enterprise applications, operating systems and network control systems, which are all examples of software that can be used to help businesses scale their IT infrastructure.\n\n**Requirements:** Most computer scientists need both a bachelor''s and a master''s degree to become experts in software development and maintenance. They learn and practice skills in technical problem-solving, diagnosis, troubleshooting and programming languages.',
    ARRAY['BSCS', 'BSIT', 'CpE'],
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'User Experience Designer',
    'DesignFlow',
    'BGC, Taguig',
    'Full-time',
    'Hybrid',
    'Design',
    '$99,082 per year',
    '**Primary duties:** A user experience (UX) designer is involved with all facets of product development regarding its purchasing, branding, usability and functionality. They collect and review user feedback to determine what a product needs to be efficient, functional and successful. They apply this feedback to the design, organization and usability. These professionals then monitor the process of testing and revising products until they meet their consumers'' high-quality standards.\n\n**Requirements:** UX designers may pursue an associate or bachelor''s degree program in an IT field and pursue additional coursework or training in design, business, web development and programming. Others may be self-taught in programming, design and development. Many employers do seek previous experience so an internship or portfolio may help these professionals secure employment.',
    ARRAY['BSIT', 'BSCS', 'Multimedia Arts'],
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Database Administrator',
    'DataVault Systems',
    'Quezon City',
    'Full-time',
    'On-site',
    'Data Management',
    '$94,537 per year',
    '**Primary duties:** Database administrators employ specialized software to organize and keep track of data. The software can be associated with software configuration, security and performance when applicable. These professionals frequently diagnose and solve complex IT issues related to the data infrastructure to ensure an organization''s data is safe, accessible and easy to navigate.\n\n**Requirements:** Database administrators typically need to earn a bachelor''s degree in computer science or management information systems. They often start as a database analyst or a developer before moving into this role so they can obtain experience in data collection and working within a network''s databases.',
    ARRAY['BSIT', 'BSCS'],
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Data Scientist',
    'Analytics Wise',
    'Makati City',
    'Full-time',
    'Hybrid',
    'Data Science',
    '$119,380 per year',
    '**Primary duties:** A data scientist analyzes and organizes data to determine trends that can influence business decisions. Their methods and IT tools use statistics and machine learning to help collect and process a company''s data such as financial records, sales, prospects and lead generation.\n\n**Requirements:** Many of these professionals choose to pursue both a bachelor''s and a master''s degree in IT or other business fields. Some pursue additional degrees, coursework and certifications that relate to their specific industry, such as healthcare.',
    ARRAY['BSCS', 'BSMath', 'BSStat'],
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Computer Scientist',
    'Advanced Research Labs',
    'Remote',
    'Full-time',
    'Remote',
    'Research & Development',
    '$107,614 per year',
    '**Primary duties:** A computer scientist applies their technological skills and resources to solve IT problems for businesses. They write new software to complete tasks in a quick and efficient period as well as develop new functions that can be of use for employees or clients.\n\n**Requirements:** Most computer scientists need to have a bachelor''s degree but employers may require a master''s degree as well. Previous work experience may also be valuable to prospective employers.',
    ARRAY['BSCS'],
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'IT Director',
    'Enterprise Corp.',
    'BGC, Taguig',
    'Full-time',
    'On-site',
    'Executive / Management',
    '$124,113 per year',
    '**Primary duties:** An IT director oversees the strategy and execution of IT operations for an organization. They ensure that department tasks align with the company''s goals and development. These professionals may also collaborate with other internal IT professionals as well as executive management to generate contingency plans, budgets and development goals.\n\n**Requirements:** This position may require a graduate degree and relevant industry certifications, such as in certain programs or applicable management courses. Entry and mid-level roles in IT support and database architecture can provide these professionals with the well-rounded experience to help them advance to this management position.',
    ARRAY['Master in IT', 'MBA'],
    'active',
    (SELECT id FROM auth.users LIMIT 1)
);
